[package]
name = "name/your_project"
version = "0.1.0"
license = "MIT"
private = true

[target]
environment = "luau"

[scripts]
start = "mayari"
dev = "mayari --dev"

[dependencies]
common = { name = "mayari/common", version = "^" }
adpt = { name = "mayari/adpt", version = "^" }
