[package]
name = "name/your_project"
version = "0.1.0"
license = "MIT"

[target]
environment = "luau"

[tools]
lune = "lune-org/lune@0.10.5"
lute = "luau-lang/lute@1.0.0"
zune = "Scythe-Technology/zune@0.5.8"
mayari = "mayari-org/mayari-cli@0.0.3"

[scripts]

[dependencies]
common = { name = "mayari/common", version = "^" }
adpt = { name = "mayari/adpt", version = "^" }
