[package]
name = "mayari/cli"
version = "0.0.5"
description = "A cli tool for mayari."
authors = ["mayari-org"]
license = "MIT"

[target]
environment = "luau"
main = "src/init.luau"
includes = ["src", "LICENSE", "README.md", "lpm.toml", "lpm.lock"]

[scripts]
build = "zune run script/build"
dev = "zune run script/dev"
update = "zune run script/update"

[tools]
zune = "Scythe-Technology/zune@0.5.8"
stylua = "JohnnyMorganz/StyLua@2.5.2"
selene = "Kampfkarren/selene@0.31.0"

[dependencies]
adpt = { name = "mayari/adpt", version = "^" }
