[tools]
lune = "lune-org/lune@0.10.5"
stylua = "JohnnyMorganz/StyLua@2.5.2"
selene = "Kampfkarren/selene@0.31.0"
mayari = "mayari-org/mayari-cli@0.0.4"

[scripts]
start = "mayari start"
dev = "mayari dev"

[dependencies]
mayari = { name = "mayari/core", version = "^" }
common = { name = "mayari/common", version = "^" }
