[tools]
lute = "luau-lang/lute@1.0.0"
stylua = "JohnnyMorganz/StyLua@2.5.2"
selene = "Kampfkarren/selene@0.31.0"
mayari = "mayari-org/mayari-cli@0.0.3"

[scripts]
start = "mayari start"
dev = "mayari dev"

[dependencies]
mayari = { name = "mayari/core", version = "^" }
common = { name = "mayari/common", version = "^" }
