[tools]
zune = "Scythe-Technology/zune@0.5.8"
stylua = "JohnnyMorganz/StyLua@2.5.2"
selene = "Kampfkarren/selene@0.31.0"
mayari = "mayari-org/mayari-cli@0.0.5"

[scripts]
build = "mayari build"
start = "zune run .mayari/src/main"
dev = "mayari dev"

[dependencies]
mayari = { name = "mayari/core", version = "^" }
common = { name = "mayari/common", version = "^" }
